curl -X 'PATCH' \
  'http://localhost:8787/api/config/oidc_authority' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 123' \
  -H 'Content-Type: application/json' \
  -d '{
  "value": "https://auth.zhr.one/application/o/trip-tracker/"
}'

curl -X 'PATCH' \
  'http://localhost:8787/api/config/oidc_client_id' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 123' \
  -H 'Content-Type: application/json' \
  -d '{
  "value": "9FbtspzZkyBQfCUCCtZbj38eKrMRFn26cwpu2D3C"
}'

curl -X 'PATCH' \
  'http://localhost:8787/api/config/oidc_scope' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 123' \
  -H 'Content-Type: application/json' \
  -d '{
  "value": "openid profile tracker"
}'

curl -X 'PATCH' \
  'http://localhost:8787/api/config/oidc_client_secret' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 123' \
  -H 'Content-Type: application/json' \
  -d '{
  "value": "2N4NUkJgIJMA7k0Ovwv9OdpQG5DF0stYfExUZCq5o1ZPnN4jZ2D0UCiDNFQYLXfkC9zgOC3MqbB9lP8x94J6UgCAwECmJbfAGwvcznuXRRVDq3luoFlpQaNv0UalEK9x"
}'
